### ISSUE TITLE
trying to create fileId

### ISSUE THREAD

**Issue by hadi500** [danog/tg-file-decoder#1]
hi, i'm trying to create fileId and this is my code : 

my data is for profile photo (photo_small).

$photo = new PhotoSizeSourceThumbnail();
$photo->setThumbFileType(1);
$photo->setThumbType('a');

$fileId = new FileId;
$fileId->setType(1);
$fileId->setId(xxxxx);
$fileId->setVolumeId(xxxx);
$fileId->setLocalId(xxxx);
$fileId->setDcId(xxx);
$fileId->setAccessHash(xxxx);
$fileId->setPhotoSizeSource($photo);

$encoded = (string)  $fileId;

and trying  to send file_id with bot (sendPhoto) and i'm get error ::

{"ok":false,"error_code":400,"description":"Bad Request: wrong remote file id specified: can't unserialize it"}

where is my problem ? thanks

**Comment by danog** [comment]
Avoid using manual type IDs, use the provided constants, instead.
Also, are you sure you want to use a profile picture?

**Comment by hadi500** [comment]
> 
> 
> Avoid using manual type IDs, use the provided constants, instead.
> Also, are you sure you want to use a profile picture?

yes
I saved my profile picture information like: ID,VolumeId,LocalId and ... (with mtproto api)
i need create Fileid and send it to someone with my bot (sendPhoto method)

Is this possible at all? also i try use the provided constants but still : can't unserialize it on bot api

**Comment by danog** [comment]
Try decoding a file ID obtained from the bot API and comparing the parameters (just var_dump it)

**Comment by hadi500** [comment]
> 
> 
> Try decoding a file ID obtained from the bot API and comparing the parameters (just var_dump it)

thanks danog,i found the problem, Type 2 Work. but bot cannot sent that file id.

I think i understood something, i can't create file id with user's access hash (I do not have access to the user, i just have data like access_hash,localid and ...) and send that photo with bot to someone. becuse every user has unique access hash and just that user can send photo.

is that correct ?

To clarify : 

1- i saved user's picture data : AccessHash, DcId, VolumeId and ... and i do not have access to the user, i just have pictures information.

2- i want create file id with that data and send photo to someone with bot.

**Comment by danog** [comment]
That is correct, file IDs generated by one user/bot cannot be reused by another user/bot.
